### CREATE NEW USER
POST http://localhost:3000/user HTTP/1.1
content-type: application/json

{
    "name": "New user",
    "lastName": "user lastname",
    "email": "user@email.com",
    "rut": "new rut"
}

### UPDATE USER
PUT http://localhost:3000/user/63b340af9709b7ab377bd285 HTTP/1.1
content-type: application/json

{
    "name": "user update"
}

### GET USER BY RUT
GET http://localhost:3000/user/new rut HTTP/1.1
content-type: application/json

### DELETE USER BY ID
DELETE http://localhost:3000/user/63b340af9709b7ab377bd285 HTTP/1.1
content-type: application/json


### CREATE NEW PERMISION
POST http://localhost:3000/permission HTTP/1.1
content-type: application/json

{
    "name": "New permission",
    "permissionIds": ["63b77cb1d501bee01d955f14"]
}

### UPDATE PERMISION
PUT http://localhost:3000/permission/63b340af9709b7ab377bd285 HTTP/1.1
content-type: application/json

{
    "name": "permission update",
}

### GET PERMISSION BY ID
GET http://localhost:3000/permission/63b62b3f8023d79ec3957973 HTTP/1.1
content-type: application/json

### DELETE PERMISSION BY ID
DELETE http://localhost:3000/permission/63b77cb1d501bee01d955f14 HTTP/1.1
content-type: application/json


### CREATE NEW ROLE
POST http://localhost:3000/role HTTP/1.1
content-type: application/json

{
    "name": "New role",
    "permissionIds": ["63b77cb1d501bee01d955f14"]
}

### UPDATE ROLE
PUT http://localhost:3000/role/63b340af9709b7ab377bd285 HTTP/1.1
content-type: application/json

{
    "name": "role update"
}

### GET ROLE BY ID
GET http://localhost:3000/role/63b77daabc1e7ea30f70333c HTTP/1.1
content-type: application/json

### DELETE ROLE BY ID
DELETE http://localhost:3000/role/63b77daabc1e7ea30f70333c HTTP/1.1
content-type: application/json


### Register
POST http://localhost:3000/auth/register HTTP/1.1
content-type: application/json

{
    "name": "New user 2",
    "lastName": "user lastname",
    "email": "user2@email.com",
    "rut": "new rut 2",
    "password": "1234",
    "roleId": "63bad6805ef2c7f54a84aeb2"
}

### Register
POST http://localhost:3000/auth/login HTTP/1.1
content-type: application/json

{
    "email": "user2@email.com",
    "password": "1234"
}
